# Generated by Django 5.2.1 on 2025-05-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_searchhistory_session_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('geonameid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('asciiname', models.CharField(max_length=200)),
                ('alternatenames', models.TextField(blank=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('country_code', models.CharField(max_length=2)),
                ('population', models.BigIntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='weather_cit_name_db5943_idx'), models.Index(fields=['asciiname'], name='weather_cit_asciina_96fa23_idx')],
            },
        ),
    ]
