# Generated by Django 5.2.1 on 2025-05-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='admin1_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='city',
            name='timezone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['country_code'], name='weather_cit_country_ff04a2_idx'),
        ),
    ]
