# Generated by Django 5.2.1 on 2025-05-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_city_admin1_code_city_timezone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='admin1_code',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
