# Generated by Django 5.2.1 on 2025-05-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_alter_city_admin1_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='citystat',
            name='city_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='city_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
